---
 - hosts: centos
   become: yes
   become_user: root
   tasks:
     - name: "Cloning  git repo to local directory /jenkin"
       git:
        repo: 'https://github.com/kamal24111991/ContinuousIntegration.git'
        dest: /jenkin/
        clone: yes
        update: no
     - name:  "Installing maven"
       yum:
        name: maven
        state: latest
        update_cache: yes
     - name: "building package"
       command: mvn package install
       args: 
        chdir: /jenkin/Spring3HibernateApp/
         
...

